In [36]:
import pandas as pd

In [ ]:
# Load cleaned datasets using relative paths
orders_df = pd.read_csv("../data/cleaned/orders_cl.csv")
orderlines_df = pd.read_csv("../data/cleaned/orderlines_cl.csv")
products_df = pd.read_csv("../data/cleaned/products_cl.csv")

In [38]:
orders = orders_df.copy()
orderlines = orderlines_df.copy()
products = products_df.copy()

In [39]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 226904 entries, 0 to 226903
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226904 non-null  int64
 1   created_date  226904 non-null  str
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  str
dtypes: float64(1), int64(1), str(2)
memory usage: 6.9 MB

In [40]:
orderlines.info()

<class 'pandas.DataFrame'>
RangeIndex: 216250 entries, 0 to 216249
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                216250 non-null  int64
 1   id_order          216250 non-null  int64
 2   product_id        216250 non-null  int64
 3   product_quantity  216250 non-null  int64
 4   sku               216250 non-null  str
 5   unit_price        216250 non-null  float64
 6   date              216250 non-null  str
dtypes: float64(1), int64(4), str(2)
memory usage: 11.5 MB

In [41]:
orders["created_date"] = pd.to_datetime(orders["created_date"])

In [42]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 226904 entries, 0 to 226903
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226904 non-null  int64
 1   created_date  226904 non-null  datetime64[us]
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 6.9 MB

In [43]:
orders_filter = orders.copy()

In [44]:
orders_filter.loc[:,"month"] = orders["created_date"].dt.month
orders

        order_id        created_date  total_paid            state
0         241319 2017-01-02 13:35:40       44.99        Cancelled
1         241423 2017-11-06 13:10:02      136.15        Completed
2         242832 2017-12-31 17:40:03       15.76        Completed
3         243330 2017-02-16 10:59:38       84.98        Completed
4         243784 2017-11-24 13:35:19      157.86        Cancelled
...          ...                 ...         ...              ...
226899    527397 2018-03-14 13:56:38       42.99      Place Order
226900    527398 2018-03-14 13:57:25       42.99  Shopping Basket
226901    527399 2018-03-14 13:57:34      141.58  Shopping Basket
226902    527400 2018-03-14 13:57:41       19.98  Shopping Basket
226903    527401 2018-03-14 13:58:36       18.98      Place Order

[226904 rows x 4 columns]

In [45]:
orders_filter.loc[:,"year"] = orders["created_date"].dt.year
orders.head()

   order_id        created_date  total_paid      state
0    241319 2017-01-02 13:35:40       44.99  Cancelled
1    241423 2017-11-06 13:10:02      136.15  Completed
2    242832 2017-12-31 17:40:03       15.76  Completed
3    243330 2017-02-16 10:59:38       84.98  Completed
4    243784 2017-11-24 13:35:19      157.86  Cancelled

strftime

In [46]:
orders_filter.loc[:,"date_as_str"] = orders["created_date"].dt.strftime("%Y-%m-%d")
orders.head()

   order_id        created_date  total_paid      state
0    241319 2017-01-02 13:35:40       44.99  Cancelled
1    241423 2017-11-06 13:10:02      136.15  Completed
2    242832 2017-12-31 17:40:03       15.76  Completed
3    243330 2017-02-16 10:59:38       84.98  Completed
4    243784 2017-11-24 13:35:19      157.86  Cancelled

datetime aggregation
mim and max

In [47]:
orders["created_date"].min(),orders["created_date"].max()

(Timestamp('2017-01-01 00:07:19'), Timestamp('2018-03-14 13:58:36'))

In [48]:
orders["created_date"].max() - orders["created_date"].min()

Timedelta('437 days 13:51:17')

Describe tables

In [49]:
orders_filter["created_date"].describe()

count                        226904
mean     2017-09-06 14:58:03.124224
min             2017-01-01 00:07:19
25%      2017-05-17 08:01:00.750000
50%      2017-10-16 21:00:01.500000
75%      2017-12-24 15:56:53.250000
max             2018-03-14 13:58:36
Name: created_date, dtype: object

## Date Filtering

In [50]:
date_filtering_df = orders.copy()
date_filtering_df.head()

   order_id        created_date  total_paid      state
0    241319 2017-01-02 13:35:40       44.99  Cancelled
1    241423 2017-11-06 13:10:02      136.15  Completed
2    242832 2017-12-31 17:40:03       15.76  Completed
3    243330 2017-02-16 10:59:38       84.98  Completed
4    243784 2017-11-24 13:35:19      157.86  Cancelled

filtering in daytime

In [51]:
date_filtering_df["created_date"] = pd.to_datetime(date_filtering_df["created_date"])

In [52]:
date_filtering_df.loc[date_filtering_df["created_date"].dt.year==2018, :].head()

    order_id        created_date  total_paid      state
11    247524 2018-01-09 14:21:34      167.98  Completed
27    256434 2018-02-26 07:32:21       39.99    Pending
29    256799 2018-02-16 09:44:42       20.97  Completed
33    258155 2018-01-22 18:51:50       40.76  Completed
51    264244 2018-01-29 15:33:06      141.97  Completed

in months. eg in March

In [53]:
date_filtering_df.loc[date_filtering_df["created_date"].dt.month==3, :].head()

    order_id        created_date  total_paid      state
39    259638 2017-03-02 20:12:59      387.60    Pending
72    271587 2017-03-08 17:23:47       20.98    Pending
73    271644 2017-03-01 13:11:40       21.98    Pending
74    272512 2018-03-04 11:35:15      114.98  Completed
85    279405 2017-03-12 19:01:08       59.98    Pending

all orders in a month . eg March

In [54]:
date_filtering_df.loc[
     (date_filtering_df["created_date"].dt.month==3) & 
                      (date_filtering_df["created_date"].dt.year==2018),
                      :].head()

       order_id        created_date  total_paid      state
74       272512 2018-03-04 11:35:15      114.98  Completed
140      294278 2018-03-04 20:04:01      173.98  Completed
25299    324779 2018-03-02 15:08:16     1874.99  Completed
37506    336990 2018-03-03 23:08:42      223.97  Completed
44901    344394 2018-03-09 16:47:11       39.98  Completed

## filtering between two dates

In [55]:
date_filtering_df.loc[
     date_filtering_df["created_date"].between("2018-03-01", "2018-04-01")
                          ].head()

       order_id        created_date  total_paid      state
74       272512 2018-03-04 11:35:15      114.98  Completed
140      294278 2018-03-04 20:04:01      173.98  Completed
25299    324779 2018-03-02 15:08:16     1874.99  Completed
37506    336990 2018-03-03 23:08:42      223.97  Completed
44901    344394 2018-03-09 16:47:11       39.98  Completed

grouping daytime with .resample()

In [56]:
orderlines["date"] = pd.to_datetime(orderlines["date"])

In [57]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 226904 entries, 0 to 226903
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226904 non-null  int64
 1   created_date  226904 non-null  datetime64[us]
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 6.9 MB

In [58]:
orderlines.info()

<class 'pandas.DataFrame'>
RangeIndex: 216250 entries, 0 to 216249
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                216250 non-null  int64
 1   id_order          216250 non-null  int64
 2   product_id        216250 non-null  int64
 3   product_quantity  216250 non-null  int64
 4   sku               216250 non-null  str
 5   unit_price        216250 non-null  float64
 6   date              216250 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(4), str(1)
memory usage: 11.5 MB

In [59]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 9992 entries, 0 to 9991
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sku       9992 non-null   str
 1   name      9992 non-null   str
 2   desc      9992 non-null   str
 3   price     9992 non-null   float64
 4   in_stock  9992 non-null   int64
 5   type      9946 non-null   str
dtypes: float64(1), int64(1), str(4)
memory usage: 468.5 KB

In [60]:
 order

NameError: name 'order' is not defined

In [ ]:
orders["order_id"].nunique(), orderlines["id_order"].nunique()

(226904, 170213)

In [ ]:
unique_skus = orderlines['sku'].unique()
orderlines

,id,id_order,product_quantity,sku,unit_price,date
0,1119109,299539,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,1,JBL0104,23.74,2017-01-01 01:06:38
...,...,...,...,...,...,...
216245,1650199,527398,1,JBL0122,42.99,2018-03-14 13:57:25
216246,1650200,527399,1,PAC0653,141.58,2018-03-14 13:57:34
216247,1650201,527400,2,APP0698,9.99,2018-03-14 13:57:41
216248,1650202,527388,1,BEZ0204,19.99,2018-03-14 13:58:01
216249,1650203,527401,1,APP0927,13.99,2018-03-14 13:58:36

In [ ]:
## Check for SKUs in orderlines that aren't in the products table
missing_skus = orderlines[~orderlines['sku'].isin(products['sku'])]
print(f"Rows with unknown SKUs: {len(missing_skus)}")

Rows with unknown SKUs: 6557

In [ ]:
# Orders where the total paid is greater than the average
high_value_orders = orders[orders['total_paid'] > orders['total_paid'].mean()]
orders

        order_id        created_date  total_paid            state
0         241319 2017-01-02 13:35:40       44.99        Cancelled
1         241423 2017-11-06 13:10:02      136.15        Completed
2         242832 2017-12-31 17:40:03       15.76        Completed
3         243330 2017-02-16 10:59:38       84.98        Completed
4         243784 2017-11-24 13:35:19      157.86        Cancelled
...          ...                 ...         ...              ...
226899    527397 2018-03-14 13:56:38       42.99      Place Order
226900    527398 2018-03-14 13:57:25       42.99  Shopping Basket
226901    527399 2018-03-14 13:57:34      141.58  Shopping Basket
226902    527400 2018-03-14 13:57:41       19.98  Shopping Basket
226903    527401 2018-03-14 13:58:36       18.98      Place Order

[226904 rows x 4 columns]

In [ ]:

# Filter for a specific date range
mask = (orders['created_date'] >= '2017-01-01') & (orders['created_date'] <= '2017-03-31')
q1_orders = orders.loc[mask]
orders

        order_id        created_date  total_paid            state
0         241319 2017-01-02 13:35:40       44.99        Cancelled
1         241423 2017-11-06 13:10:02      136.15        Completed
2         242832 2017-12-31 17:40:03       15.76        Completed
3         243330 2017-02-16 10:59:38       84.98        Completed
4         243784 2017-11-24 13:35:19      157.86        Cancelled
...          ...                 ...         ...              ...
226899    527397 2018-03-14 13:56:38       42.99      Place Order
226900    527398 2018-03-14 13:57:25       42.99  Shopping Basket
226901    527399 2018-03-14 13:57:34      141.58  Shopping Basket
226902    527400 2018-03-14 13:57:41       19.98  Shopping Basket
226903    527401 2018-03-14 13:58:36       18.98      Place Order

[226904 rows x 4 columns]

In [ ]:
# Filter for orders in 2017 only
orders_2017 = orders[orders['created_date'].dt.year == 2017]

In [ ]:
# Filtering the orders dataframe
orders_completed = orders.loc[orders['state'] == 'Completed'].copy()

In [ ]:
# Keep only rows where the SKU exists in the products dataframe
orderlines = orderlines.loc[orderlines['sku'].isin(products['sku'])].copy()

In [ ]:
# Sync orders one last time (in case an order now has 0 valid products)
final_ids = orderlines['id_order'].unique()
orders = orders.loc[orders['order_id'].isin(final_ids)].copy()

In [ ]:
orders["state"].value_counts()

state
Shopping Basket    82635
Completed          42259
Place Order        22995
Pending            12936
Cancelled           5319
Name: count, dtype: int64

In [ ]:
# keep only completed orders
orders = orders.loc[orders["state"] == "Completed", :]

In [ ]:
orderlines["id_order"].nunique()

166283

In [ ]:
orders.info()

<class 'pandas.DataFrame'>
Index: 42259 entries, 1 to 226614
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      42259 non-null  int64
 1   created_date  42259 non-null  datetime64[us]
 2   total_paid    42259 non-null  float64
 3   state         42259 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 1.6 MB

In [ ]:
orders_orderlines = orders.merge(orderlines, how="inner", left_on="order_id", right_on="id_order")
orders_orderlines

,order_id,created_date,total_paid,state,id,id_order,product_quantity,sku,unit_price,date
0,241423,2017-11-06 13:10:02,136.15,Completed,1398738,241423,1,LAC0212,129.16,2017-11-06 12:47:20
1,242832,2017-12-31 17:40:03,15.76,Completed,1529178,242832,1,PAR0074,10.77,2017-12-31 17:26:40
2,243330,2017-02-16 10:59:38,84.98,Completed,1181923,243330,1,OWC0074,77.99,2017-02-15 17:07:44
3,245275,2017-06-28 11:35:37,149.00,Completed,1276706,245275,1,TAD0007,149.00,2017-06-28 11:12:30
4,245595,2017-01-21 12:52:47,112.97,Completed,1154394,245595,2,PAC1561,52.99,2017-01-21 12:49:00
...,...,...,...,...,...,...,...,...,...,...
55315,527042,2018-03-14 11:47:50,18.98,Completed,1649446,527042,1,APP0927,13.99,2018-03-14 11:42:38
55316,527070,2018-03-14 11:50:48,24.97,Completed,1649512,527070,2,APP0698,9.99,2018-03-14 11:49:01
55317,527074,2018-03-14 11:51:42,24.97,Completed,1649522,527074,2,APP0698,9.99,2018-03-14 11:49:36
55318,527096,2018-03-14 11:58:40,34.96,Completed,1649565,527096,3,APP0698,9.99,2018-03-14 11:54:35
55319,527112,2018-03-14 12:03:52,14.98,Completed,1649593,527112,1,APP0698,9.99,2018-03-14 11:58:13

In [ ]:
print(f"Unique Orders: {orders['order_id'].nunique()}")
print(f"Unique Products (SKUs): {orderlines['sku'].nunique()}")

Unique Orders: 42259
Unique Products (SKUs): 6430

In [ ]:
# Top 10 products by quantity sold
top_products = orderlines.groupby('sku')['product_quantity'].sum().sort_values(ascending=False).head(10)

# Top 10 products by revenue contribution
orderlines['line_total'] = orderlines['product_quantity'] * orderlines['unit_price']
top_revenue_skus = orderlines.groupby('sku')['line_total'].sum().sort_values(ascending=False).head(10)

In [ ]:
top_revenue_skus

sku
APP2485    750258.56
APP2477    587757.54
APP2483    544797.75
APP2072    475077.70
APP1970    428289.77
APP2446    375354.65
APP2479    370322.42
APP2484    358153.98
LGE0044    356538.38
APP1190    312303.18
Name: line_total, dtype: float64

In [ ]:
total_revenue = orders['total_paid'].sum()
print(f"Total Revenue: ${total_revenue:,.2f}")

Total Revenue: $8,341,580.47

In [ ]:
# Calculate revenue per line item
orderlines['revenue'] = orderlines['product_quantity'] * orderlines['unit_price']

# Top 10 SKUs by Revenue
top_rev_products = orderlines.groupby('sku')['revenue'].sum().sort_values(ascending=False).head(10)
top_rev_products

sku
APP2485    750258.56
APP2477    587757.54
APP2483    544797.75
APP2072    475077.70
APP1970    428289.77
APP2446    375354.65
APP2479    370322.42
APP2484    358153.98
LGE0044    356538.38
APP1190    312303.18
Name: revenue, dtype: float64

In [ ]:
# Comparison of revenue by state
revenue_leakage = orders.groupby('state')['total_paid'].sum()
revenue_leakage

state
Completed    8341580.47
Name: total_paid, dtype: float64

In [ ]:
total_skus = products['sku'].nunique()
full_price_skus = total_skus - discounted_skus_count

print(f"Percentage of catalog ever discounted: {(discounted_skus_count / total_skus) * 100:.2f}%")